export const fakedata = [
    {
      "account_id": "87Mj1JEo9aHRJ9y55NoqUN4zJNDlXeCw8nwpN",
      "account_owner": null,
      "amount": 16.75,
      "authorized_date": null,
      "category": [
        "Food and Drink",
        "Restaurants"
      ],
      "category_id": "13005000",
      "date": "2020-08-23",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Tectra Inc",
      "name": "Tectra Inc",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "wpaX7Rm68ytBo1DkkvwKIoAgZEkPlgTrV5D39",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "87Mj1JEo9aHRJ9y55NoqUN4zJNDlXeCw8nwpN",
      "account_owner": null,
      "amount": 20.78,
      "authorized_date": null,
      "category": [
        "Payment"
      ],
      "category_id": "16000000",
      "date": "2020-08-22",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Morro Bay Golf Club",
      "name": "Morro Bay Golf Club",
      "payment_channel": "other",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "ka9QKMWR8LTRExloovw8UkvEl6DmVEHWpXgq3",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "87Mj1JEo9aHRJ9y55NoqUN4zJNDlXeCw8nwpN",
      "account_owner": null,
      "amount": 5.62,
      "authorized_date": null,
      "category": [
        "Food and Drink",
        "Restaurants",
        "Fast Food"
      ],
      "category_id": "13005032",
      "date": "2020-08-22",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "KFC",
      "name": "KFC",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "JzlNrwDy7AFWPrgAAyEzhREp9wlX1pfdJ9W1P",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "87Mj1JEo9aHRJ9y55NoqUN4zJNDlXeCw8nwpN",
      "account_owner": null,
      "amount": 15,
      "authorized_date": null,
      "category": [
        "Shops",
        "Sporting Goods"
      ],
      "category_id": "19046000",
      "date": "2020-08-22",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Madison Bicycle Shop",
      "name": "Madison Bicycle Shop",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "5NeMQnmX93fQ7nWrrd53Hr4GVX6Z5GtZdWebl",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "ojqm31n6w8foEmA778DeSVwzdVnJ9riRbjR5r",
      "account_owner": null,
      "amount": 25,
      "authorized_date": null,
      "category": [
        "Payment",
        "Credit Card"
      ],
      "category_id": "16001000",
      "date": "2020-08-13",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Tacqueria Santa Cruz",
      "name": "Tacqueria Santa Cruz",
      "payment_channel": "other",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "XM7VZbW3jqIkAZEvvGRrHKEZQdDqjZHdE3z9Q",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "p7KRxMn6WEHeVABmm86jTBDJZBN9XziLzwLjK",
      "account_owner": null,
      "amount": 5.4,
      "authorized_date": null,
      "category": [
        "Travel",
        "Taxi"
      ],
      "category_id": "22016000",
      "date": "2020-08-13",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Uber",
      "name": "Uber 063015 SF**POOL**",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "mNRXzMn68ofBoaKwwvA8IJvokypLqoiLJWw9y",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "EAmByVDLkoFKxAwMMaQ9SQ8oBQdVjwSXmyXez",
      "account_owner": null,
      "amount": 3.21,
      "authorized_date": null,
      "category": [
        "Transfer",
        "Debit"
      ],
      "category_id": "21006000",
      "date": "2020-08-12",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Campus Bottle",
      "name": "Campus Bottle *324",
      "payment_channel": "other",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": "ACH",
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "KBqNzADLlGFmjzAooVelhnVkDdpoBkfVNLWK6",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "gBnayMWDmQFanAD66VrZSQg5oQkEebSg5ogRP",
      "account_owner": null,
      "amount": 25,
      "authorized_date": null,
      "category": [
        "Transfer",
        "Deposit"
      ],
      "category_id": "21007000",
      "date": "2020-08-12",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Avila Beach Golf Club",
      "name": "Avila Beach Golf Club",
      "payment_channel": "other",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "VQPyeZDzNVfvAeokkq7buNvlL3pJdlFWdwLom",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "87Mj1JEo9aHRJ9y55NoqUN4zJNDlXeCw8nwpN",
      "account_owner": null,
      "amount": 46.2,
      "authorized_date": null,
      "category": [
        "Recreation",
        "Gyms and Fitness Centers"
      ],
      "category_id": "17018000",
      "date": "2020-08-11",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Chevron",
      "name": "Chevron #342",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "l4vQrmnRypfyEdkVV8QeUJyMVGgqnMiZ7kGnz",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "p7KRxMn6WEHeVABmm86jTBDJZBN9XziLzwLjK",
      "account_owner": null,
      "amount": 6.89,
      "authorized_date": null,
      "category": [
        "Travel",
        "Airlines and Aviation Services"
      ],
      "category_id": "22001000",
      "date": "2020-08-11",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Uber",
      "name": "Uber #2342",
      "payment_channel": "other",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "ygNWQkn68vHgEnzAAw1dSjD7GXNMn7FyAlLoR",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "p7KRxMn6WEHeVABmm86jTBDJZBN9XziLzwLjK",
      "account_owner": null,
      "amount": 12,
      "authorized_date": null,
      "category": [
        "Food and Drink",
        "Restaurants",
        "Fast Food"
      ],
      "category_id": "13005032",
      "date": "2020-08-10",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": "3322"
      },
      "merchant_name": "McDonald's",
      "name": "McDonald's",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "9e1MLREo94iW7g1mmP9LhXEnxoJZ1nuRD5bkp",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "p7KRxMn6WEHeVABmm86jTBDJZBN9XziLzwLjK",
      "account_owner": null,
      "amount": 4.33,
      "authorized_date": null,
      "category": [
        "Food and Drink",
        "Restaurants",
        "Coffee Shop"
      ],
      "category_id": "13005043",
      "date": "2020-08-10",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Starbucks",
      "name": "Starbucks",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "vLdWjgn68mcw1eRQQvn9I8Z7EkRoA7tWRE4gD",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "p7KRxMn6WEHeVABmm86jTBDJZBN9XziLzwLjK",
      "account_owner": null,
      "amount": 39.5,
      "authorized_date": null,
      "category": [
        "Food and Drink",
        "Restaurants"
      ],
      "category_id": "13005000",
      "date": "2020-08-09",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Shell",
      "name": "Shell San Luis Obispo",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "RPdyNwDlxkuLKNPkkowxuGoRdV9waRTR4Brwv",
      "transaction_type": "place",
      "unofficial_currency_code": null
    },
    {
      "account_id": "ojqm31n6w8foEmA778DeSVwzdVnJ9riRbjR5r",
      "account_owner": null,
      "amount": 4.22,
      "authorized_date": null,
      "category": [
        "Transfer",
        "Credit"
      ],
      "category_id": "21005000",
      "date": "2020-08-08",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": 'Starbucks',
      "name": "Starbucks",
      "payment_channel": "other",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "DWbzmnDEdpsnWerMM43jHdRGV34jxGtvQk97o",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "87Mj1JEo9aHRJ9y55NoqUN4zJNDlXeCw8nwpN",
      "account_owner": null,
      "amount": 9.35,
      "authorized_date": null,
      "category": [
        "Travel",
        "Airlines and Aviation Services"
      ],
      "category_id": "22001000",
      "date": "2020-07-29",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "High St Deli",
      "name": "High Street Deli",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "qer1dJy68WiywJ377v8VU7g61WPbx6SdMZAL8",
      "transaction_type": "special",
      "unofficial_currency_code": null
    },
    {
      "account_id": "p7KRxMn6WEHeVABmm86jTBDJZBN9XziLzwLjK",
      "account_owner": null,
      "amount": 6.33,
      "authorized_date": null,
      "category": [
        "Travel",
        "Taxi"
      ],
      "category_id": "22016000",
      "date": "2020-07-27",
      "iso_currency_code": "USD",
      "location": {
        "address": null,
        "city": null,
        "country": null,
        "lat": null,
        "lon": null,
        "postal_code": null,
        "region": null,
        "store_number": null
      },
      "merchant_name": "Uber",
      "name": "Uber 072515 SF**POOL**",
      "payment_channel": "in store",
      "payment_meta": {
        "by_order_of": null,
        "payee": null,
        "payer": null,
        "payment_method": null,
        "payment_processor": null,
        "ppd_id": null,
        "reason": null,
        "reference_number": null
      },
      "pending": false,
      "pending_transaction_id": null,
      "transaction_code": null,
      "transaction_id": "6PQbZnEk9xuGb6ZzzanxUQdgnjVyMgIg3yMmW",
      "transaction_type": "special",
      "unofficial_currency_code": null
    }
  ]