/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "plaidapi",
            "endpoint": "https://mdf9us7vic.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        },
        {
            "name": "plaidaccessapi",
            "endpoint": "https://jh9gs0xdj8.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        },
        {
            "name": "addAccessToken",
            "endpoint": "https://cwchzykbvl.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        },
        {
            "name": "getransactionsapi",
            "endpoint": "https://5mu94x2gqd.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        },
        {
            "name": "cleanandcategorizeapi",
            "endpoint": "https://r5rz4ofl65.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        },
        {
            "name": "updateCategoriesApi",
            "endpoint": "https://diiz7gmeil.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "UserDB-dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
